feat: Add more information to instrument scientists view of proposal
UserOfficeProject/user-office-frontend pull request #951
Opened 2022-06-09 13:19 UTC by bolmsten

## Description

Feedback received from the last proposal round contained request for emails and comments to be visible to the instrument scientist

![Screenshot 2022-06-09 at 15 09 05](https://user-images.githubusercontent.com/6403388/172864368-eca250d2-fb23-4edd-9e8c-c3e017563181.png)

![Screenshot 2022-06-09 at 15 08 56](https://user-images.githubusercontent.com/6403388/172864384-b5abfa50-d297-4520-b8a3-88fdff7abd3e.png)

## Motivation and Context

## How Has This Been Tested

## Fixes

## Changes

## Depends on

https://github.com/UserOfficeProject/user-office-backend/pull/680

## Tests included/Docs Updated?

- [ ] I have added tests to cover my changes.
- [ ] All relevant doc has been updated

2022-06-09 13:22 UTC, martin-trajanovski requested changes

2022-06-09 13:22 UTC, martin-trajanovski commented on src/components/review/ProposalQuestionaryReview.tsx
> +  console.log(data.users, data.proposer);
This console should be removed

2022-06-09 13:39 UTC, bolmsten commented on src/components/review/ProposalQuestionaryReview.tsx
> +  console.log(data.users, data.proposer);
Thanks, fixed

2022-06-10 10:06 UTC, martin-trajanovski approved these changes

2022-06-22 10:04 UTC, keiranjprice101 approved these changes

2022-06-23 20:32 UTC, merged