add settings to control default proposal filters
UserOfficeProject/user-office-frontend pull request #968
Opened 2022-07-15 15:25 UTC by vyshnavi1605

## Description
closes: https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/620

## Motivation and Context
Instrument scientists at STFC have to change this to "All proposals" and the status to "All" every time they use the page.

## How Has This Been Tested
Logged on as an Instrument Scientist in the stfc side and tested the view and logged on as an instrument scientist in the ess side and tested the view. Also logged on as a User Officer to check the enabled features. 

![image](https://user-images.githubusercontent.com/72739242/179253875-ca061e20-80e8-4478-b348-f0a965112550.png)
ESS scientist 

![image](https://user-images.githubusercontent.com/72739242/179254011-e2d50cb7-a8b7-450c-9474-62aaecb987f5.png)
STFC scientist 

## Fixes
Fixes: https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/620

## Changes
- Used `PROPOSAL_FILTER` flag to set what filters the instrument scientist should see upon logging in
- Regenerated sdk

## Depends on
https://github.com/UserOfficeProject/user-office-backend/pull/703

## Tests included/Docs Updated?

- [ ] I have added tests to cover my changes.
- [ ] All relevant doc has been updated

2022-07-18 08:22 UTC, TickleThePanda commented on src/components/proposal/ProposalTableInstrumentScientist.tsx
> +      featureContext.featuresMap.get(FeatureId.PROPOSAL_FILTER)?.isEnabled
Could a setting be better than a feature here? The setting could define `DEFAULT_INST_SCI_STATUS_FILTER` and map properly to the names.

2022-07-18 08:22 UTC, TickleThePanda commented on src/components/proposal/ProposalTableInstrumentScientist.tsx
> +      featureContext.featuresMap.get(FeatureId.PROPOSAL_FILTER)?.isEnabled
Could a separate setting be better than a feature here, too? The setting could define `DEFAULT_INST_SCI_REVIEWER_FILTER` and map to the names?

2022-07-22 12:12 UTC, martin-trajanovski approved these changes

2022-07-26 16:05 UTC, vyshnavi1605 commented on src/components/proposal/ProposalTableInstrumentScientist.tsx
> +  if (!statusFilter && statusFilter != 0) {
`!statusFilter` didn't seem to be allowing `statusFilter = 0` so it was defaulting to 2, so I added that extra check in. But `statusFilter === undefined` alone seems to be working fine, so I'll change that.

2022-07-26 16:32 UTC, vyshnavi1605 commented on src/components/proposal/ProposalTableInstrumentScientist.tsx
> +const proposalStatusFilter = new Map<Maybe<string> | undefined, Scalars['Int']>(
I've tried this, but I get the error `This expression is not callable. Type 'Number' has no call signatures` on the line `let statusFilter = proposalStatusFilter.get(statusFilterValue);` I've tried a few things to fix it but it doesn't seem to work.

2022-07-28 12:21 UTC, TickleThePanda commented on src/components/proposal/ProposalTableInstrumentScientist.tsx
> +const proposalStatusFilter = new Map<Maybe<string> | undefined, Scalars['Int']>(
Ah, sorry - that line would have to be `let statusFilter = proposalStatusFilter[statusFilterValue]` by changing it to a `Record`.

2022-07-28 12:21 UTC, TickleThePanda commented on src/components/proposal/ProposalTableInstrumentScientist.tsx
> +  if (!statusFilter && statusFilter != 0) {
I think `statusFilter === undefined || statusFilter === null` is clearer.

2022-07-29 07:36 UTC, TickleThePanda requested changes

2022-07-29 07:36 UTC, TickleThePanda commented on src/components/review/ReviewerFilter.tsx
> +export const reviewFilter = new Map<Maybe<string> | undefined, ReviewerFilter>([
I forgot to say, I think it's worth using a record here, too.

2022-08-02 08:14 UTC, TickleThePanda requested changes

2022-08-02 08:14 UTC, TickleThePanda commented on cypress/integration/appSettings.ts
>  context('App settings tests', () => {
Sorry for additional changes. As we've been talking about test coverage, I think these features could need integration tests.

2022-08-15 11:59 UTC, martin-trajanovski approved these changes
This seems good to me. 👀 👍

2022-08-16 08:13 UTC, TickleThePanda approved these changes

2022-08-16 08:15 UTC, merged